name: Label and Assign PRs
on:
  pull_request:
    types:
      - opened
jobs:
  label_and_assign_PRs:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - run: |
          gh pr edit "$NUMBER" --add-label "$LABELS"
          gh pr edit "$NUMBER" --add-assignee "$ASSIGNEE"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          LABELS: needs review
          ASSIGNEE: @me
